image:
  name: glillico/docker-ubuntu2404-ansible:latest

before_script:
  - pip3 install ansible-lint
  - pip3 install molecule

stages:
  - lint
  - test

lint_job:
  stage: lint
  before_script:
  - pip3 install ansible-lint
  script:
    - ansible-lint .

molecule:
  stage: test
  image: python:3.12

  services:
    - name: docker:dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - python3 -m pip install --upgrade pip
    - pip install ansible molecule docker requests
    - docker version

  script:
    - molecule converge