default:
  tags:
    - linux-ansible

stages:
  - lint

ansible_lint:
  stage: lint
  before_script:
    - python3 -m venv .venv
    - . .venv/bin/activate
    - pip install --upgrade pip
    - pip install ansible ansible-lint
  script:
    - . .venv/bin/activate
    - ansible-lint .