image:
  name: glillico/docker-ubuntu2404-ansible:latest

before_script:
  - pip3 install ansible-lint
  - pip3 install molecule

stages:
  - lint
  - test

lint_job:
  stage: lint
  before_script:
  - pip3 install ansible-lint
  script:
    - ansible-lint .

test_job:
  stage: test
  before_script:
    - pip3 install molecule
  script:
    - molecule converge