#SPDX-License-Identifier: MIT-0
---
# tasks file for prometheus
- name: Prometheus installig 
  get_url:
    url: https://github.com/prometheus/prometheus/releases/tag/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    mode: '0777'

- name: Unarchive a file
  unarchive:
    src: /tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /usr/local/bin/
