---
- name: Check if prometheus installed
  ansible.builtin.command: which prometheus
  ignore_errors: true
  register: prometheus_installed
  tags: skip_ansible_lint

- name: Install prometheus
  ansible.builtin.include_tasks:
    file: install.yml
  when: prometheus_installed.rc == 1

- name: Provision prometheus
  ansible.builtin.include_tasks:
    file: provision_node_exporter.yml
  when: provision == "node_exporter"
